# Generated by Django 5.2.8 on 2025-11-29 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_table_reservation_booking_time_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
